# render.yaml
services:
  - type: web
    name: discord-ai-bot
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: DISCORD_TOKEN
        value:  $(DISCORD_TOKEN)
      - key: OPENROUTER_API_KEY
        value: $(OPENROUTER_API_KEY)

